version: '3.2'

services:
   mysql:
      image: mysql:8.0
      restart: always
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: jossidev
      command: --default-authentication-plugin=mysql_native_password
   phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: mysql
        UPLOAD_LIMIT: 30000000
      links:
        - mysql
